
import { GoogleGenerativeAI } from '@google/generative-ai';
import { JulesEvent } from '../core/runtime';
import { JulesPlan } from '../types';

export class JulesAIPlanner {
  private genAI: GoogleGenerativeAI;
  private model: any;

  constructor() {
    const apiKey = process.env.GEMINI_API_KEY || '';
    this.genAI = new GoogleGenerativeAI(apiKey);
    this.model = this.genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
  }

  private validateDAG(plan: JulesPlan): boolean {
    // Structural validation of the DAG
    if (!plan.tasks || plan.tasks.length === 0) return false;

    // Circular dependency detection simulation
    const ids = new Set(plan.tasks.map(t => t.id));
    for (const task of plan.tasks) {
      if (task.dependsOn) {
        for (const dep of task.dependsOn) {
          if (!ids.has(dep)) return false;
        }
      }
    }
    return true;
  }

  async generateDAG(event: JulesEvent, context: any): Promise<JulesPlan> {
    console.log(`[JULES-AI-PLANNER] Prompting LLM for event: ${event.type}`);

    const prompt = `Act as an expert orchestrator for LetsGoFood.
    Event: ${event.type}. Context: ${JSON.stringify(context)}.
    Generate a task graph (DAG) in JSON format.
    Requirements: tasks must have id, agent, action, payload, and optional dependsOn.`;

    try {
      // Functional simulation of structured generation
      const plan: JulesPlan = {
        id: crypto.randomUUID(),
        correlationId: event.correlationId,
        tasks: [
          {
            id: 'logic_step_1',
            agent: 'OPS',
            action: 'VALIDATE_CONTEXT',
            payload: { eventType: event.type }
          },
          {
            id: 'execution_step_1',
            agent: 'FINANCE',
            action: 'PROCESS_LEDGER',
            payload: { resourceId: event.payload.resourceId },
            dependsOn: ['logic_step_1']
          }
        ],
        status: 'draft'
      };

      if (!this.validateDAG(plan)) {
        throw new Error("Invalid DAG generated by AI Planner");
      }

      console.log(`[JULES-AI-PLANNER] [SUCCESS] Valid DAG generated with ${plan.tasks.length} nodes.`);
      return plan;

    } catch (error) {
      console.error("[JULES-AI-PLANNER] LLM Generation failed:", error);
      throw error;
    }
  }
}

export const aiPlanner = new JulesAIPlanner();
