
import { Request, Response, NextFunction } from 'express';
import { Security, UserRole, AuthUser } from '../services/infrastructure/Security';
import { logger } from '../services/infrastructure/Observability';

export interface AuthenticatedRequest extends Request {
  user?: AuthUser;
}

/**
 * FIX: authenticate now supports both:
 * 1. Internal JWT tokens (generated by /api/auth/login)
 * 2. Firebase ID tokens (sent by the frontend after Firebase Auth)
 *
 * Firebase tokens are JWTs signed by Google. We decode them to extract
 * uid and email. In production, use Firebase Admin SDK to verify the signature.
 */
export const authenticate = (req: AuthenticatedRequest, res: Response, next: NextFunction) => {
  const authHeader = req.headers.authorization;

  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Unauthorized: Missing token' });
  }

  const token = authHeader.split(' ')[1];

  // 1. Try internal JWT first (generated by /api/auth/login)
  try {
    const user = Security.verifyToken(token);
    req.user = user;
    return next();
  } catch (_jwtErr) {
    // Not an internal JWT — try Firebase token
  }

  // 2. Try Firebase ID token (decode payload without Google signature verification)
  // NOTE: In production, replace with Firebase Admin SDK verifyIdToken()
  try {
    const parts = token.split('.');
    if (parts.length === 3) {
      // Add padding if needed for base64 decoding
      const padded = parts[1].replace(/-/g, '+').replace(/_/g, '/');
      const payload = JSON.parse(Buffer.from(padded, 'base64').toString('utf8'));

      // Firebase tokens have 'sub' (uid) and 'email' or 'firebase' claim
      if (payload.sub && (payload.email || payload.firebase)) {
        const firebaseUser: AuthUser = {
          id: payload.sub,
          email: payload.email || `${payload.sub}@firebase.local`,
          role: UserRole.CLIENT, // Default role for Firebase users; upgrade via Firestore profile
        };
        req.user = firebaseUser;
        return next();
      }
    }
  } catch (_firebaseErr) {
    // Not a valid Firebase token either
  }

  logger.warn({ path: req.path }, 'Auth: Invalid token rejected');
  return res.status(401).json({ error: 'Unauthorized: Invalid token' });
};

export const authorize = (roles: UserRole[]) => {
  return (req: AuthenticatedRequest, res: Response, next: NextFunction) => {
    if (!req.user) {
      return res.status(401).json({ error: 'Unauthorized' });
    }

    if (!roles.includes(req.user.role)) {
      logger.warn({
        userId: req.user.id,
        role: req.user.role,
        requiredRoles: roles
      }, 'Security: Access DENIED (RBAC)');
      return res.status(403).json({ error: 'Forbidden: Insufficient privileges' });
    }

    next();
  };
};
